# Generated by Django 3.1.4 on 2020-12-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0002_auto_20180801_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='BookingName',
            field=models.CharField(default='BookingName', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='PubName',
            field=models.CharField(default='PubName', max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='PartySize',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
