# Generated by Django 3.1.4 on 2020-12-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0003_auto_20201214_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Time',
            field=models.TimeField(default='00:00', verbose_name='%H:%M'),
        ),
    ]
