# Generated by Django 3.1.4 on 2020-12-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0004_userdetails_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='PartySize',
            field=models.IntegerField(default='1', max_length=1),
        ),
    ]
