# Generated by Django 3.1.4 on 2020-12-14 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0005_auto_20201214_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='PartySize',
            field=models.IntegerField(default='1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
