# Generated by Django 3.1.4 on 2020-12-16 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0006_auto_20201214_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='BookingName',
            field=models.CharField(default='Type Here', help_text='Probably the surname of your party', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='PartySize',
            field=models.IntegerField(default='1', help_text='Due to current government reulations this has a maximum value of 6', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='PubName',
            field=models.CharField(default='Select One', max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Time',
            field=models.TimeField(default='00:00', help_text='Please enter time in 24hr clock format (HH:MM)', verbose_name='%H:%M'),
        ),
    ]
