# Generated by Django 3.1.4 on 2020-12-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0007_auto_20201216_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='PubName',
            field=models.CharField(choices=[('Select One', 'SELECT ONE'), ('Black Bull', 'BLACK BULL'), ('Brads Bar', 'BRADS BAR'), ('Ivy House', 'IVY HOUSE')], default='Select One', max_length=255),
        ),
    ]
