# Generated by Django 3.1.4 on 2020-12-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0009_choice_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
