# Generated by Django 3.1.4 on 2020-12-16 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0010_auto_20201216_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='TableNo',
            field=models.IntegerField(default='1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='BookingName',
            field=models.CharField(help_text='Probably the surname of your party', max_length=100),
        ),
    ]
