# Generated by Django 3.1.4 on 2020-12-17 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0011_auto_20201216_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='BookingName',
            field=models.CharField(blank=True, help_text='Probably the surname of your party', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='PartySize',
            field=models.IntegerField(blank=True, default='1', help_text='Due to current government reulations this has a maximum value of 6', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='PubName',
            field=models.CharField(blank=True, choices=[('Black Bull', 'BLACK BULL'), ('Brads Bar', 'BRADS BAR'), ('Ivy House', 'IVY HOUSE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='TableNo',
            field=models.IntegerField(blank=True, default='1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Time',
            field=models.TimeField(blank=True, default='09:00', help_text='Please enter time in 24hr clock format (HH:MM)', verbose_name='%H:%M'),
        ),
    ]
