# Generated by Django 3.1.4 on 2020-12-18 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0014_auto_20201218_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='TableNo',
            field=models.IntegerField(blank=True, default='1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
