# Generated by Django 3.1.4 on 2020-12-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0015_auto_20201218_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Time',
            field=models.CharField(blank=True, default='09:00', help_text='Please select a time in 24hr clock format (HH:MM) from the drop down', max_length=11),
        ),
    ]
